<a href="https://colab.research.google.com/github/BimalGhimire38/Extra_Python_Stuffs/blob/main/DL_Revision.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Deep Learning Revision
2082/12/10  10:02 PM

In [1]:
import torch
print(torch.__version__)

2.10.0+cu128


In [2]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")

else:
  print("GPU not available")


GPU is available
Using GPU: Tesla T4


# Creating Tensor

In [4]:
# Using Empty
a=torch.empty(2,3)
# just assigns space to the tensor

In [5]:
# CHeck type
type(a)

torch.Tensor

In [6]:
# Zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
# Using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
# UsinG Rand
torch.rand(2,3)

tensor([[0.6706, 0.7242, 0.7866],
        [0.3881, 0.2898, 0.0927]])

We can use manual seed for reproducibility while using rand

In [10]:
# Use of Seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [11]:
# Using a tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [13]:
# Other Ways
# Arange
torch.arange(0,10,1)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
torch.linspace(0,10,10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [16]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [20]:
torch.full((3,3),7)

tensor([[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]])

Tensor Shapes

In [22]:
x = torch.tensor([[1,2,3],[4,5,6]])

In [23]:
x.shape

torch.Size([2, 3])

In [26]:
x.shape[1]

3

In [27]:
# crating an empty tensor of similar size
torch.empty_like(x)

tensor([[              0, 134547656189072,        11662568],
        [             97,       807129920, 134553688354096]])

In [29]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [30]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [32]:
# torch.rand_like(x)

# Tensor Data Types

In [33]:
x.dtype

torch.int64

In [34]:
# asssign data type
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [35]:
torch.tensor([1,2,3],dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [36]:
# Using to
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [38]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])