<a href="https://colab.research.google.com/github/BimalGhimire38/Extra_Python_Stuffs/blob/main/DL_Revision.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Deep Learning Revision
2082/12/10  10:02 PM

In [1]:
import torch
print(torch.__version__)

2.10.0+cu128


In [2]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")

else:
  print("GPU not available")


GPU is available
Using GPU: Tesla T4


# Creating Tensor

In [4]:
# Using Empty
a=torch.empty(2,3)
# just assigns space to the tensor

In [5]:
# CHeck type
type(a)

torch.Tensor

In [6]:
# Zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
# Using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
# UsinG Rand
torch.rand(2,3)

tensor([[0.6706, 0.7242, 0.7866],
        [0.3881, 0.2898, 0.0927]])