<a href="https://colab.research.google.com/github/BimalGhimire38/Extra_Python_Stuffs/blob/main/DL_Revision.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Deep Learning Revision
2082/12/10  10:02 PM

In [1]:
import torch
print(torch.__version__)

2.10.0+cu128


In [2]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")

else:
  print("GPU not available")


GPU is available
Using GPU: Tesla T4


# Creating Tensor

In [4]:
# Using Empty
a=torch.empty(2,3)
# just assigns space to the tensor

In [5]:
# CHeck type
type(a)

torch.Tensor

In [6]:
# Zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
# Using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
# UsinG Rand
torch.rand(2,3)

tensor([[0.6706, 0.7242, 0.7866],
        [0.3881, 0.2898, 0.0927]])

We can use manual seed for reproducibility while using rand

In [10]:
# Use of Seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [11]:
# Using a tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [13]:
# Other Ways
# Arange
torch.arange(0,10,1)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
torch.linspace(0,10,10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [16]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [20]:
torch.full((3,3),7)

tensor([[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]])

Tensor Shapes

In [22]:
x = torch.tensor([[1,2,3],[4,5,6]])

In [23]:
x.shape

torch.Size([2, 3])

In [26]:
x.shape[1]

3

In [27]:
# crating an empty tensor of similar size
torch.empty_like(x)

tensor([[              0, 134547656189072,        11662568],
        [             97,       807129920, 134553688354096]])

In [29]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [30]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [32]:
# torch.rand_like(x)

# Tensor Data Types

In [33]:
x.dtype

torch.int64

In [34]:
# asssign data type
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [35]:
torch.tensor([1,2,3],dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [36]:
# Using to
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [38]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

# Mathematical Operations

# Tensor - Scalar Operations

In [41]:
x=torch.rand(2,2)
x

tensor([[0.9969, 0.7565],
        [0.2239, 0.3023]])

In [42]:
x+2

tensor([[2.9969, 2.7565],
        [2.2239, 2.3023]])

In [43]:
x-2

tensor([[-1.0031, -1.2435],
        [-1.7761, -1.6977]])

In [44]:
x*2

tensor([[1.9938, 1.5130],
        [0.4478, 0.6047]])

In [45]:
x/2

tensor([[0.4984, 0.3783],
        [0.1119, 0.1512]])

In [46]:
(x*100)//3

tensor([[33., 25.],
        [ 7., 10.]])

In [47]:
((x*100)//3)%2

tensor([[1., 1.],
        [1., 0.]])

In [48]:
# Power
x**2

tensor([[0.9938, 0.5723],
        [0.0501, 0.0914]])

## Tensor - Tensor operations

In [51]:
a = torch.rand(2,2)
a

tensor([[0.2426, 0.7003],
        [0.5277, 0.2472]])

In [52]:
b=torch.rand(2,2)
b

tensor([[0.7909, 0.4235],
        [0.0169, 0.2209]])

In [53]:
a+b

tensor([[1.0334, 1.1238],
        [0.5446, 0.4681]])

In [54]:
a-b

tensor([[-0.5483,  0.2769],
        [ 0.5108,  0.0263]])

In [55]:
a*b

tensor([[0.1918, 0.2966],
        [0.0089, 0.0546]])

In [56]:
a/b

tensor([[ 0.3067,  1.6537],
        [31.2257,  1.1190]])

In [57]:
a//b

tensor([[ 0.,  1.],
        [31.,  1.]])

In [58]:
a%b

tensor([[0.2426, 0.2769],
        [0.0038, 0.0263]])

In [60]:
c=torch.tensor([1,-2,3,-5,])

In [61]:
torch.abs(c)

tensor([1, 2, 3, 5])

In [62]:
torch.neg(c)

tensor([-1,  2, -3,  5])

In [63]:
d=torch.tensor([1.9,2.3,2.7,4.5,3.1])

In [64]:
torch.round(d)

tensor([2., 2., 3., 4., 3.])

In [65]:
torch.ceil(d)

tensor([2., 3., 3., 5., 4.])

In [67]:
torch.floor(d)

tensor([1., 2., 2., 4., 3.])

In [68]:
torch.clamp(d,2,3)

tensor([2.0000, 2.3000, 2.7000, 3.0000, 3.0000])

In [69]:
## Reduction Operation

In [76]:
e = torch.randint(size=(2,3), low=0, high=4, dtype=torch.float32)

In [77]:
e

tensor([[3., 3., 1.],
        [3., 1., 1.]])

In [78]:
torch.sum(e)

tensor(12.)

In [79]:
torch.sum(e,dim=0)

tensor([6., 4., 2.])

In [80]:
torch.sum(e,dim=1)

tensor([7., 5.])

In [81]:
torch.mean(e)

tensor(2.)

In [82]:
torch.mean(e,dim=0)

tensor([3., 2., 1.])

In [83]:
torch.median(e)

tensor(1.)

In [84]:
torch.max(e)

tensor(3.)

In [85]:
torch.min(e)

tensor(1.)

In [87]:
torch.prod(e,dim=1)

tensor([9., 3.])

In [89]:
torch.var(e)

tensor(1.2000)

In [90]:
torch.argmax(e)

tensor(0)

In [91]:
torch.argmin(e)

tensor(2)

In [98]:
f=(torch.ones(3,3))*4
g=torch.rand_like(f)

In [99]:
# matrix multliplication
torch.matmul(f,g)


tensor([[5.1752, 8.5236, 8.3966],
        [5.1752, 8.5236, 8.3966],
        [5.1752, 8.5236, 8.3966]])

In [100]:
v1=torch.tensor([1,2])
v2 = torch.tensor([3,4])

In [101]:
# dot product

In [102]:
torch.dot(v1,v2)

tensor(11)

In [103]:
# Transpose

In [113]:
h= torch.randint(size=(3,3),low=3,high=7,dtype=torch.float32)

In [114]:
h

tensor([[5., 4., 5.],
        [4., 3., 4.],
        [5., 5., 4.]])

In [115]:
torch.transpose(h,1,0)

tensor([[5., 4., 5.],
        [4., 3., 5.],
        [5., 4., 4.]])

In [116]:
# Determinant
torch.det(h)

tensor(1.0000)

In [118]:
# Inverse
torch.inverse(h)

tensor([[-8.0000,  9.0000,  1.0000],
        [ 4.0000, -5.0000, -0.0000],
        [ 5.0000, -5.0000, -1.0000]])

# Comparision Operations

In [119]:
i = torch.randint(size=(2,3),low=1,high=9)
j = torch.randint(size=(2,3),low=0,high=15)

In [120]:
i

tensor([[6, 5, 3],
        [1, 4, 4]])

In [121]:
j

tensor([[11,  0, 14],
        [ 9, 11,  1]])

In [122]:
i>j

tensor([[False,  True, False],
        [False, False,  True]])

In [123]:
i<j

tensor([[ True, False,  True],
        [ True,  True, False]])

In [124]:
i==j

tensor([[False, False, False],
        [False, False, False]])

In [125]:
i!=j

tensor([[True, True, True],
        [True, True, True]])

# Special Functions

In [136]:
k =torch.randint(size=(2,3),low=5,high=15,dtype=torch.float32)

In [137]:
k

tensor([[ 5.,  5.,  7.],
        [ 7.,  8., 12.]])

In [138]:
torch.log(k)

tensor([[1.6094, 1.6094, 1.9459],
        [1.9459, 2.0794, 2.4849]])

In [139]:
torch.exp(k)

tensor([[1.4841e+02, 1.4841e+02, 1.0966e+03],
        [1.0966e+03, 2.9810e+03, 1.6275e+05]])

In [140]:
torch.sqrt(k)

tensor([[2.2361, 2.2361, 2.6458],
        [2.6458, 2.8284, 3.4641]])

In [141]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9933, 0.9933, 0.9991],
        [0.9991, 0.9997, 1.0000]])

In [142]:
torch.softmax(k,dim=0)

tensor([[0.1192, 0.0474, 0.0067],
        [0.8808, 0.9526, 0.9933]])

In [143]:
# Relu
torch.relu(k)

tensor([[ 5.,  5.,  7.],
        [ 7.,  8., 12.]])