<a href="https://colab.research.google.com/github/BimalGhimire38/Extra_Python_Stuffs/blob/main/Revision_PyTorch_NN_Module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

2082/12/13  05:42 PM
Balen Shah became 43rd PM of Nepal

# Binary Classification with 5 input feature

In [1]:
import torch
import torch.nn as nn


class Model(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)

    return out



In [2]:
# Create dataset
features = torch.rand(10,5)

# Create Model
model = Model(features.shape[1])

# Forward pass
model(features)


tensor([[0.3590],
        [0.3406],
        [0.4537],
        [0.3959],
        [0.4281],
        [0.3436],
        [0.4347],
        [0.3101],
        [0.3539],
        [0.3510]], grad_fn=<SigmoidBackward0>)

In [3]:
model.linear.weight

Parameter containing:
tensor([[ 0.1447,  0.4407, -0.1712, -0.1480, -0.3979]], requires_grad=True)

In [4]:
model.linear.bias

Parameter containing:
tensor([-0.4036], requires_grad=True)

# Visualizing the Computationsl Graphs

In [5]:
! pip install torchinfo

In [8]:
from torchinfo import summary
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# Model with Hidden Layers

In [9]:
import torch
import torch.nn as nn


class Model(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.linear1 = nn.Linear(num_features,3)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear1(features)
    out = self.relu(out)
    out = self.linear2(out)
    out=self.sigmoid(out)

    return out

In [10]:
# Create dataset
features = torch.rand(10,5)

# Create Model
model = Model(features.shape[1])

# Forward pass
model(features)

tensor([[0.4050],
        [0.3836],
        [0.3886],
        [0.3787],
        [0.3949],
        [0.3841],
        [0.3872],
        [0.3740],
        [0.3710],
        [0.3857]], grad_fn=<SigmoidBackward0>)

In [11]:
model.linear1.weight

Parameter containing:
tensor([[-0.0883,  0.0272, -0.0927, -0.2096, -0.1599],
        [ 0.3746, -0.3079,  0.2887, -0.1652,  0.1410],
        [-0.3544, -0.0090,  0.2214, -0.1938,  0.1290]], requires_grad=True)

In [12]:
model.linear2.weight

Parameter containing:
tensor([[ 0.0116, -0.1106,  0.3859]], requires_grad=True)

In [14]:
from torchinfo import summary
summary(model, input_Size=(10,5))

Layer (type:depth-idx)                   Param #
Model                                    --
├─Linear: 1-1                            18
├─ReLU: 1-2                              --
├─Linear: 1-3                            4
├─Sigmoid: 1-4                           --
Total params: 22
Trainable params: 22
Non-trainable params: 0

# Sequential Containers

In [ ]:
import torch
import torch.nn as nn


class Model(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.linear1 = nn.Linear(num_features,3)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear1(features)
    out = self.relu(out)
    out = self.linear2(out)
    out=self.sigmoid(out)

    return out