<a href="https://colab.research.google.com/github/BimalGhimire38/Extra_Python_Stuffs/blob/main/Revision_PyTorch_Training_Pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

2082/11/12  08:38 AM

In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')

In [3]:
df.values

array([[842302, 'M', 17.99, ..., 0.4601, 0.1189, nan],
       [842517, 'M', 20.57, ..., 0.275, 0.08902, nan],
       [84300903, 'M', 19.69, ..., 0.3613, 0.08758, nan],
       ...,
       [926954, 'M', 16.6, ..., 0.2218, 0.0782, nan],
       [927241, 'M', 20.6, ..., 0.4087, 0.124, nan],
       [92751, 'B', 7.76, ..., 0.2871, 0.07039, nan]], dtype=object)

In [4]:
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN


In [5]:
df.shape

(569, 33)

In [6]:
df.drop(columns=['id','Unnamed: 32'], inplace=True)

In [7]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678


# Train Test Split

In [8]:
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:,1:], df.iloc[:,0], test_size=0.2)

# Scaling

In [9]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [10]:
x_train

array([[ 1.1468287 ,  0.13124089,  1.11270376, ...,  1.20342963,
         0.25029229, -0.05333976],
       [-0.69762709, -0.28468398, -0.72553348, ..., -0.68349323,
        -1.47429243, -0.85078244],
       [ 2.21541942,  0.56524945,  2.25026761, ...,  1.97930252,
        -0.26151995,  0.05971819],
       ...,
       [-1.59655061, -0.18070276, -1.58736174, ..., -1.79454321,
         0.37586113, -0.19164365],
       [-1.49622813, -0.82267375, -1.39570696, ..., -1.19774178,
        -1.99246258, -0.40788069],
       [ 1.26050856, -0.40674888,  1.28168969, ...,  1.89550825,
         1.42014883,  0.39505025]])

In [11]:
y_train

,diagnosis
6,M
297,M
369,M
513,B
351,M
...,...
79,B
218,M
314,B
116,B


# Label Encoding

In [12]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [13]:
y_train

array([1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,

In [14]:
x_train

array([[ 1.1468287 ,  0.13124089,  1.11270376, ...,  1.20342963,
         0.25029229, -0.05333976],
       [-0.69762709, -0.28468398, -0.72553348, ..., -0.68349323,
        -1.47429243, -0.85078244],
       [ 2.21541942,  0.56524945,  2.25026761, ...,  1.97930252,
        -0.26151995,  0.05971819],
       ...,
       [-1.59655061, -0.18070276, -1.58736174, ..., -1.79454321,
         0.37586113, -0.19164365],
       [-1.49622813, -0.82267375, -1.39570696, ..., -1.19774178,
        -1.99246258, -0.40788069],
       [ 1.26050856, -0.40674888,  1.28168969, ...,  1.89550825,
         1.42014883,  0.39505025]])

In [15]:
x_train_tensor = torch.from_numpy(x_train)
x_test_tensor = torch.from_numpy(x_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [16]:
x_train_tensor

tensor([[ 1.1468,  0.1312,  1.1127,  ...,  1.2034,  0.2503, -0.0533],
        [-0.6976, -0.2847, -0.7255,  ..., -0.6835, -1.4743, -0.8508],
        [ 2.2154,  0.5652,  2.2503,  ...,  1.9793, -0.2615,  0.0597],
        ...,
        [-1.5966, -0.1807, -1.5874,  ..., -1.7945,  0.3759, -0.1916],
        [-1.4962, -0.8227, -1.3957,  ..., -1.1977, -1.9925, -0.4079],
        [ 1.2605, -0.4067,  1.2817,  ...,  1.8955,  1.4201,  0.3951]],
       dtype=torch.float64)

In [17]:
x_train_tensor.shape

torch.Size([455, 30])

In [18]:
x_test_tensor.shape

torch.Size([114, 30])

# Defining the Model

In [33]:
class MySimpleNN():

  def __init__(self,x):

    self.weights = torch.rand(x.shape[1],1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)


  def forward(self, x):
    z = torch.matmul(x, self.weights)+self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)
    loss = -(y*torch.log(y_pred)+(1-y)*torch.log(1-y_pred)).mean()
    return loss

# Importand Parameters

In [34]:
learning_rate = 0.1
epochs = 25

# Training Pipeline

In [44]:
# create models
model = MySimpleNN(x_train_tensor)
# define loop
for epoch in range(epochs):
  # forward pass
  y_pred = model.forward(x_train_tensor)
  # print(y_pred)

  # loss calculation
  loss = model.loss_function(y_pred,y_train_tensor)
  # print(f"Epoch: {epoch+1}, Loss: {loss.item()}")
  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.weights -= learning_rate*model.weights.grad
    model.bias -= learning_rate*model.bias.grad

  # print(f"Updated Weights {model.weights}")
  # print(f"Updated Bias {model.bias}")
  # Zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # Print loss in each epoch
  print(f"Epoch: {epoch+1}, Loss: {loss.item()}")




Epoch: 1, Loss: 3.0459973573785257
Epoch: 2, Loss: 2.8953221244748506
Epoch: 3, Loss: 2.743767315714456
Epoch: 4, Loss: 2.590267055921022
Epoch: 5, Loss: 2.434101592692174
Epoch: 6, Loss: 2.275272448008443
Epoch: 7, Loss: 2.1147280385675056
Epoch: 8, Loss: 1.9554645700421402
Epoch: 9, Loss: 1.8012173686382495
Epoch: 10, Loss: 1.65665801388401
Epoch: 11, Loss: 1.521328000908894
Epoch: 12, Loss: 1.3960433206561451
Epoch: 13, Loss: 1.2846730666239101
Epoch: 14, Loss: 1.188167589531353
Epoch: 15, Loss: 1.1069419982279733
Epoch: 16, Loss: 1.0406594986984963
Epoch: 17, Loss: 0.9880501640693585
Epoch: 18, Loss: 0.946936710419819
Epoch: 19, Loss: 0.9147211639474568
Epoch: 20, Loss: 0.8890514574936844
Epoch: 21, Loss: 0.8681312188015151
Epoch: 22, Loss: 0.8506862555173792
Epoch: 23, Loss: 0.8358322923132853
Epoch: 24, Loss: 0.8229568903297199
Epoch: 25, Loss: 0.8116333217070738


In [46]:
model.bias

tensor([-0.1810], dtype=torch.float64, requires_grad=True)

# Evaluation


In [51]:
with torch.no_grad():
  y_pred = model.forward(x_test_tensor)
  y_pred = (y_pred>0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
print(f"Accuracy: {accuracy.item()}")
# print(y_pred)

Accuracy: 0.5183133482933044
